(load "utils.scm")
(define (var_arg . lst)
  (if (null? lst)
    (displayln "nothing")
    (displayln lst)))
(var_arg)
(define (nested_var_arg . (arg_1 . args))
  (if (list? args)
    (begin
      (displayln "args")
      (displayln args))
    (if (arg_1)
      (displayln arg_1)
      (displayln "nothing"))))
(nested_var_arg)
(nested_var_arg "1")
(nested_var_arg "1" "2")
(nested_var_arg "1" "2" "3")