(define (outer y)
  (if (> y 0)
    (+ y 2)
    (let ()
      (define (test x)
        (* x x)
        )
      (test y)
      ))
  )
(outer -4)

; (define (test x)
;   (* x x)
;   )
(define (outer y)
  (if (> y 0)
    (+ y 2)
    (begin
      ;; ;Definition may not be used as an expression: #[defn-item 12 #[uninterned-symbol 13 .test.1] #[expr-item 14]]
      ; (define (test x)
      ;   (* x x)
      ;   )
      (test y)
      ))
  )
(outer -4)
