(define left-parenthesis "(")
(define right-parenthesis ")")
(define (left-parenthesis? obj)
  (assert (string? obj))
  (equal? obj left-parenthesis)
  )
(define (right-parenthesis? obj)
  (assert (string? obj))
  (equal? obj right-parenthesis)
  )
