(cd "~/SICP_SDF/SDF_exercises/common-lib")
(load "logic_lib.scm")
(define (check-pred pred return-handler . elms)
  (and* pred (assert* (apply pred elms) (list pred "for" elms "fails")))
  (return-handler elms)
  )